spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batchSample
    username: postgres
    password: postgres
  sql:
    init:
      mode: always